#!/bin/bash

SUP_PLATFORMS="vck190"
SUP_DESIGNS="base-trd-platform0 base-trd-platform1 base-trd-platform2 base-trd-platform3"
PLATFORM="vck190"
DESIGN="base-trd-platform1"
SILICON="es1"

if [ ! -e ./.petalinux/metadata ]; then
	echo -e "This script must be run from the project top level"
	exit 4
fi

function print_list() {
	echo -e "Platforms:"
	for pfm in ${SUP_PLATFORMS}; do
		echo -e "  ${pfm}"
	done
	echo -e ""
	echo -e "Designs:"
	for dsgn in ${SUP_DESIGNS}; do
		echo -e "  ${dsgn}"
	done
}

function print_help() {
	echo -e "Usage:"
	echo -e "  $0 [-h|--help]"
	echo -e "Options:"
	echo -e "  -h, --help       Display this help and exit"
	echo -e "  -l, --list       List supported targets platforms and designs"
	echo -e "  -p, --platform   Target platform (default: vck190)"
	echo -e "  -d, --design     Target design (default: base-trd-platform1)"
	echo -e "  -s, --silicon    Target silicon (default: es1)"
}

while [ "$1" != "" ]; do
	case $1 in
	-h | --help )
		print_help $0
		exit 0
		;;
	-l | --list )
		print_list
		exit 0
		;;
	-p | --platform )
		shift
		PLATFORM=$1
		;;
	-d | --design )
		shift
		DESIGN=$1
		;;
	-s | --silicon )
		shift
		SILICON=$1
		;;
	*)
		echo "invalid argument '$1'"
		exit 1
		;;
	esac
	shift
done

# symlink DT
pushd project-spec/meta-user/recipes-bsp/device-tree/files > /dev/null
dt=${DESIGN}.dtsi
if [ ! -e ${dt} ]; then
	echo "device tree ${dt} not found"
	exit 6
fi
rm -f pl-custom.dtsi
ln -s ${dt} pl-custom.dtsi
popd > /dev/null

# symlink kernel-patches
pushd project-spec/meta-base-trd/recipes-kernel/linux > /dev/null
if [ $DESIGN = "base-trd-platform3" ]; then 

	if [ ! -e ${DESIGN} ]; then
		echo "kernel patch ${DESIGN} not found"
		exit 6
	fi
	rm -f linux-xlnx_%.bbappend
	ln -s ${DESIGN} linux-xlnx_%.bbappend
else 
	if [ ! -e base-trd-platform ]; then
		echo "kernel patch ${DESIGN} not found"
		exit 6
	fi
	rm -f linux-xlnx_%.bbappend
	ln -s base-trd-platform linux-xlnx_%.bbappend
	
fi
popd > /dev/null

# change hostname in config for prod versions
if [ $SILICON = "prod" ]; then
	#set host name in config
	sed -i -e "s#CONFIG_SUBSYSTEM_HOSTNAME=.*#CONFIG_SUBSYSTEM_HOSTNAME=\"\xilinx-vck190-2020_2\"\"#" \
		project-spec/configs/config
	#set product name in config
	sed -i -e "s#CONFIG_SUBSYSTEM_PRODUCT=.*#CONFIG_SUBSYSTEM_PRODUCT=\"\xilinx-vck190-2020_2\"\"#" \
		project-spec/configs/config
fi

# change platfrom name:
pushd project-spec/meta-base-trd/recipes-apps/trd-files/files > /dev/null
xocl=xocl.txt
if [ ! -e ${xocl} ]; then
	echo "text file '${xocl}' not found"
	exit 6
fi
echo ${PLATFORM}_${DESIGN//-/_} > ${xocl}
