-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.2
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity process_image is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 : OUT STD_LOGIC;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    p_src_rows_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_src_cols_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_src_data_V_V_dout : IN STD_LOGIC_VECTOR (19 downto 0);
    p_src_data_V_V_empty_n : IN STD_LOGIC;
    p_src_data_V_V_read : OUT STD_LOGIC;
    p_dst_data_V_V_din : OUT STD_LOGIC_VECTOR (19 downto 0);
    p_dst_data_V_V_full_n : IN STD_LOGIC;
    p_dst_data_V_V_write : OUT STD_LOGIC );
end;


architecture behav of process_image is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln303_reg_544 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln303_1_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_0_0_reg_186 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_0_1_reg_198 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_386_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_530 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln301_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln301_reg_539 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln303_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln303_fu_413_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln303_reg_548 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln303_1_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal add_ln303_1_fu_429_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln303_1_reg_557 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal add_ln314_fu_445_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln314_1_fu_461_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal add_ln325_fu_475_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln325_reg_578 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal GenericBPC_row_idx_v_5_reg_586 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal icmp_ln325_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal GenericBPC_row_idx_v_6_reg_591 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_7_reg_596 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_8_reg_601 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_9_reg_606 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_fu_510_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_reg_611 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_process_row_fu_326_ap_ready : STD_LOGIC;
    signal grp_process_row_fu_326_ap_done : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal grp_process_row_fu_326_ap_start : STD_LOGIC;
    signal grp_process_row_fu_326_ap_idle : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 : STD_LOGIC;
    signal grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_p_src_data_V_V_read : STD_LOGIC;
    signal grp_process_row_fu_326_p_dst_data_V_V_din : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_process_row_fu_326_p_dst_data_V_V_write : STD_LOGIC;
    signal grp_process_row_fu_326_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_row_fu_326_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret5_update_row_idx_fu_362_ap_ready : STD_LOGIC;
    signal call_ret5_update_row_idx_fu_362_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret5_update_row_idx_fu_362_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret5_update_row_idx_fu_362_ap_return_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret5_update_row_idx_fu_362_ap_return_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret5_update_row_idx_fu_362_ap_return_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_c_0_0_phi_fu_190_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_c_0_1_phi_fu_202_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal c2_0_0_reg_210 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln314_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal c2_0_1_reg_221 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln314_1_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal GenericBPC_row_idx_v_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_1_reg_244 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_2_reg_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_3_reg_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_row_idx_v_4_reg_280 : STD_LOGIC_VECTOR (7 downto 0);
    signal GenericBPC_rd_ptr_reg_292 : STD_LOGIC_VECTOR (31 downto 0);
    signal GenericBPC_wr_ptr_0_reg_302 : STD_LOGIC_VECTOR (31 downto 0);
    signal r3_0_reg_314 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_row_fu_326_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln306_fu_419_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln306_1_fu_435_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln317_fu_451_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln317_1_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln113_fu_376_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln113_fu_380_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln_fu_396_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln325_fu_472_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln325_1_fu_481_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;

    component process_row IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_num_clks_per_row_read : IN STD_LOGIC_VECTOR (15 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_rd_ptr_read : IN STD_LOGIC_VECTOR (31 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_wr_ptr_read : IN STD_LOGIC_VECTOR (31 downto 0);
        r : IN STD_LOGIC_VECTOR (15 downto 0);
        p_src_rows_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_src_data_V_V_dout : IN STD_LOGIC_VECTOR (19 downto 0);
        p_src_data_V_V_empty_n : IN STD_LOGIC;
        p_src_data_V_V_read : OUT STD_LOGIC;
        p_dst_data_V_V_din : OUT STD_LOGIC_VECTOR (19 downto 0);
        p_dst_data_V_V_full_n : IN STD_LOGIC;
        p_dst_data_V_V_write : OUT STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component update_row_idx IS
    port (
        ap_ready : OUT STD_LOGIC;
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read : IN STD_LOGIC_VECTOR (7 downto 0);
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_process_row_fu_326 : component process_row
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_row_fu_326_ap_start,
        ap_done => grp_process_row_fu_326_ap_done,
        ap_idle => grp_process_row_fu_326_ap_idle,
        ap_ready => grp_process_row_fu_326_ap_ready,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read => GenericBPC_row_idx_v_reg_232,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read => GenericBPC_row_idx_v_1_reg_244,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read => GenericBPC_row_idx_v_2_reg_256,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read => GenericBPC_row_idx_v_3_reg_268,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read => GenericBPC_row_idx_v_4_reg_280,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0 => GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0 => GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0 => GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0 => GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0 => GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 => grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_num_clks_per_row_read => trunc_ln_reg_530,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_rd_ptr_read => GenericBPC_rd_ptr_reg_292,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_wr_ptr_read => GenericBPC_wr_ptr_0_reg_302,
        r => r3_0_reg_314,
        p_src_rows_read => p_src_rows_read,
        p_src_data_V_V_dout => p_src_data_V_V_dout,
        p_src_data_V_V_empty_n => p_src_data_V_V_empty_n,
        p_src_data_V_V_read => grp_process_row_fu_326_p_src_data_V_V_read,
        p_dst_data_V_V_din => grp_process_row_fu_326_p_dst_data_V_V_din,
        p_dst_data_V_V_full_n => p_dst_data_V_V_full_n,
        p_dst_data_V_V_write => grp_process_row_fu_326_p_dst_data_V_V_write,
        ap_return_0 => grp_process_row_fu_326_ap_return_0,
        ap_return_1 => grp_process_row_fu_326_ap_return_1);

    call_ret5_update_row_idx_fu_362 : component update_row_idx
    port map (
        ap_ready => call_ret5_update_row_idx_fu_362_ap_ready,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read => GenericBPC_row_idx_v_reg_232,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read => GenericBPC_row_idx_v_1_reg_244,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read => GenericBPC_row_idx_v_2_reg_256,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read => GenericBPC_row_idx_v_3_reg_268,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read => GenericBPC_row_idx_v_4_reg_280,
        ap_return_0 => call_ret5_update_row_idx_fu_362_ap_return_0,
        ap_return_1 => call_ret5_update_row_idx_fu_362_ap_return_1,
        ap_return_2 => call_ret5_update_row_idx_fu_362_ap_return_2,
        ap_return_3 => call_ret5_update_row_idx_fu_362_ap_return_3,
        ap_return_4 => call_ret5_update_row_idx_fu_362_ap_return_4);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_process_row_fu_326_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_row_fu_326_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln325_fu_485_p2 = ap_const_lv1_1))) then 
                    grp_process_row_fu_326_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_row_fu_326_ap_ready = ap_const_logic_1)) then 
                    grp_process_row_fu_326_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    GenericBPC_rd_ptr_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_rd_ptr_reg_292 <= zext_ln301_reg_539;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_rd_ptr_reg_292 <= grp_process_row_fu_326_ap_return_0;
            end if; 
        end if;
    end process;

    GenericBPC_row_idx_v_1_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_row_idx_v_1_reg_244 <= ap_const_lv8_1;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_row_idx_v_1_reg_244 <= GenericBPC_row_idx_v_6_reg_591;
            end if; 
        end if;
    end process;

    GenericBPC_row_idx_v_2_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_row_idx_v_2_reg_256 <= ap_const_lv8_2;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_row_idx_v_2_reg_256 <= GenericBPC_row_idx_v_7_reg_596;
            end if; 
        end if;
    end process;

    GenericBPC_row_idx_v_3_reg_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_row_idx_v_3_reg_268 <= ap_const_lv8_3;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_row_idx_v_3_reg_268 <= GenericBPC_row_idx_v_8_reg_601;
            end if; 
        end if;
    end process;

    GenericBPC_row_idx_v_4_reg_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_row_idx_v_4_reg_280 <= ap_const_lv8_4;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_row_idx_v_4_reg_280 <= GenericBPC_row_idx_v_9_reg_606;
            end if; 
        end if;
    end process;

    GenericBPC_row_idx_v_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_row_idx_v_reg_232 <= ap_const_lv8_0;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_row_idx_v_reg_232 <= GenericBPC_row_idx_v_5_reg_586;
            end if; 
        end if;
    end process;

    GenericBPC_wr_ptr_0_reg_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                GenericBPC_wr_ptr_0_reg_302 <= ap_const_lv32_0;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                GenericBPC_wr_ptr_0_reg_302 <= grp_process_row_fu_326_ap_return_1;
            end if; 
        end if;
    end process;

    c2_0_0_reg_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                c2_0_0_reg_210 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln314_fu_440_p2 = ap_const_lv1_0))) then 
                c2_0_0_reg_210 <= add_ln314_fu_445_p2;
            end if; 
        end if;
    end process;

    c2_0_1_reg_221_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                c2_0_1_reg_221 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln314_1_fu_456_p2 = ap_const_lv1_0))) then 
                c2_0_1_reg_221 <= add_ln314_1_fu_461_p2;
            end if; 
        end if;
    end process;

    c_0_0_reg_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln303_reg_544 = ap_const_lv1_0))) then 
                c_0_0_reg_186 <= add_ln303_reg_548;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_0_0_reg_186 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    c_0_1_reg_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                c_0_1_reg_198 <= ap_const_lv16_0;
            elsif (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln303_1_reg_553 = ap_const_lv1_0))) then 
                c_0_1_reg_198 <= add_ln303_1_reg_557;
            end if; 
        end if;
    end process;

    r3_0_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                r3_0_reg_314 <= ap_const_lv16_2;
            elsif (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                r3_0_reg_314 <= r_reg_611;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln325_fu_485_p2 = ap_const_lv1_1))) then
                GenericBPC_row_idx_v_5_reg_586 <= call_ret5_update_row_idx_fu_362_ap_return_0;
                GenericBPC_row_idx_v_6_reg_591 <= call_ret5_update_row_idx_fu_362_ap_return_1;
                GenericBPC_row_idx_v_7_reg_596 <= call_ret5_update_row_idx_fu_362_ap_return_2;
                GenericBPC_row_idx_v_8_reg_601 <= call_ret5_update_row_idx_fu_362_ap_return_3;
                GenericBPC_row_idx_v_9_reg_606 <= call_ret5_update_row_idx_fu_362_ap_return_4;
                r_reg_611 <= r_fu_510_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                add_ln303_1_reg_557 <= add_ln303_1_fu_429_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln303_reg_548 <= add_ln303_fu_413_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                add_ln325_reg_578 <= add_ln325_fu_475_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln303_1_reg_553 <= icmp_ln303_1_fu_424_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln303_reg_544 <= icmp_ln303_fu_408_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                trunc_ln_reg_530 <= add_ln113_fu_380_p2(16 downto 1);
                    zext_ln301_reg_539(16 downto 1) <= zext_ln301_fu_404_p1(16 downto 1);
            end if;
        end if;
    end process;
    zext_ln301_reg_539(0) <= '0';
    zext_ln301_reg_539(31 downto 17) <= "000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln303_fu_408_p2, ap_enable_reg_pp0_iter0, icmp_ln303_1_fu_424_p2, ap_enable_reg_pp1_iter0, ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state12, icmp_ln325_fu_485_p2, ap_CS_fsm_state13, grp_process_row_fu_326_ap_done, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone, icmp_ln314_fu_440_p2, icmp_ln314_1_fu_456_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln303_fu_408_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln303_fu_408_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln303_1_fu_424_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln303_1_fu_424_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln314_fu_440_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln314_1_fu_456_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln325_fu_485_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if (((grp_process_row_fu_326_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1, zext_ln317_fu_451_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 <= zext_ln317_fu_451_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0_assign_proc : process(ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 <= ap_const_lv20_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1, icmp_ln314_fu_440_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln314_fu_440_p2 = ap_const_lv1_0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1, zext_ln317_1_fu_467_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 <= zext_ln317_1_fu_467_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0_assign_proc : process(ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 <= ap_const_lv20_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1, icmp_ln314_1_fu_456_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln314_1_fu_456_p2 = ap_const_lv1_0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1, zext_ln306_fu_419_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 <= zext_ln306_fu_419_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0_assign_proc : process(ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1_assign_proc : process(p_src_data_V_V_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 <= p_src_data_V_V_dout;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln303_reg_544, ap_block_pp0_stage0_11001, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln303_reg_544 = ap_const_lv1_0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1, zext_ln306_1_fu_435_p1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 <= zext_ln306_1_fu_435_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0_assign_proc : process(ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0_11001, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1_assign_proc : process(p_src_data_V_V_dout, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 <= p_src_data_V_V_dout;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln303_1_reg_553, ap_block_pp1_stage0_11001, ap_CS_fsm_state13, grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln303_1_reg_553 = ap_const_lv1_0))) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1;
        else 
            GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1;
    GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 <= grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1;
    add_ln113_fu_380_p2 <= std_logic_vector(unsigned(zext_ln113_fu_376_p1) + unsigned(ap_const_lv17_1));
    add_ln303_1_fu_429_p2 <= std_logic_vector(unsigned(ap_phi_mux_c_0_1_phi_fu_202_p4) + unsigned(ap_const_lv16_1));
    add_ln303_fu_413_p2 <= std_logic_vector(unsigned(ap_phi_mux_c_0_0_phi_fu_190_p4) + unsigned(ap_const_lv16_1));
    add_ln314_1_fu_461_p2 <= std_logic_vector(unsigned(c2_0_1_reg_221) + unsigned(ap_const_lv16_1));
    add_ln314_fu_445_p2 <= std_logic_vector(unsigned(c2_0_0_reg_210) + unsigned(ap_const_lv16_1));
    add_ln325_fu_475_p2 <= std_logic_vector(unsigned(zext_ln325_fu_472_p1) + unsigned(ap_const_lv17_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(7);
    ap_CS_fsm_state11 <= ap_CS_fsm(8);
    ap_CS_fsm_state12 <= ap_CS_fsm(9);
    ap_CS_fsm_state13 <= ap_CS_fsm(10);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
    ap_CS_fsm_state9 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln303_reg_544)
    begin
                ap_block_pp0_stage0_11001 <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln303_reg_544 = ap_const_lv1_0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln303_reg_544)
    begin
                ap_block_pp0_stage0_subdone <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln303_reg_544 = ap_const_lv1_0));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_11001_assign_proc : process(p_src_data_V_V_empty_n, ap_enable_reg_pp1_iter1, icmp_ln303_1_reg_553)
    begin
                ap_block_pp1_stage0_11001 <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln303_1_reg_553 = ap_const_lv1_0));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(p_src_data_V_V_empty_n, ap_enable_reg_pp1_iter1, icmp_ln303_1_reg_553)
    begin
                ap_block_pp1_stage0_subdone <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln303_1_reg_553 = ap_const_lv1_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(p_src_data_V_V_empty_n, icmp_ln303_reg_544)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (icmp_ln303_reg_544 = ap_const_lv1_0));
    end process;

        ap_block_state5_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp1_stage0_iter1_assign_proc : process(p_src_data_V_V_empty_n, icmp_ln303_1_reg_553)
    begin
                ap_block_state6_pp1_stage0_iter1 <= ((p_src_data_V_V_empty_n = ap_const_logic_0) and (icmp_ln303_1_reg_553 = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln303_fu_408_p2)
    begin
        if ((icmp_ln303_fu_408_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln303_1_fu_424_p2)
    begin
        if ((icmp_ln303_1_fu_424_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state12, icmp_ln325_fu_485_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln325_fu_485_p2 = ap_const_lv1_0)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_c_0_0_phi_fu_190_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln303_reg_544, c_0_0_reg_186, add_ln303_reg_548)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln303_reg_544 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_c_0_0_phi_fu_190_p4 <= add_ln303_reg_548;
        else 
            ap_phi_mux_c_0_0_phi_fu_190_p4 <= c_0_0_reg_186;
        end if; 
    end process;


    ap_phi_mux_c_0_1_phi_fu_202_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln303_1_reg_553, c_0_1_reg_198, add_ln303_1_reg_557)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln303_1_reg_553 = ap_const_lv1_0))) then 
            ap_phi_mux_c_0_1_phi_fu_202_p4 <= add_ln303_1_reg_557;
        else 
            ap_phi_mux_c_0_1_phi_fu_202_p4 <= c_0_1_reg_198;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12, icmp_ln325_fu_485_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln325_fu_485_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_row_fu_326_ap_start <= grp_process_row_fu_326_ap_start_reg;
    icmp_ln303_1_fu_424_p2 <= "1" when (ap_phi_mux_c_0_1_phi_fu_202_p4 = trunc_ln_reg_530) else "0";
    icmp_ln303_fu_408_p2 <= "1" when (ap_phi_mux_c_0_0_phi_fu_190_p4 = trunc_ln_reg_530) else "0";
    icmp_ln314_1_fu_456_p2 <= "1" when (c2_0_1_reg_221 = trunc_ln_reg_530) else "0";
    icmp_ln314_fu_440_p2 <= "1" when (c2_0_0_reg_210 = trunc_ln_reg_530) else "0";
    icmp_ln325_fu_485_p2 <= "1" when (unsigned(zext_ln325_1_fu_481_p1) < unsigned(add_ln325_reg_578)) else "0";
    p_dst_data_V_V_din <= grp_process_row_fu_326_p_dst_data_V_V_din;

    p_dst_data_V_V_write_assign_proc : process(ap_CS_fsm_state13, grp_process_row_fu_326_p_dst_data_V_V_write)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            p_dst_data_V_V_write <= grp_process_row_fu_326_p_dst_data_V_V_write;
        else 
            p_dst_data_V_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_V_V_blk_n_assign_proc : process(p_src_data_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln303_reg_544, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln303_1_reg_553)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln303_reg_544 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln303_1_reg_553 = ap_const_lv1_0)))) then 
            p_src_data_V_V_blk_n <= p_src_data_V_V_empty_n;
        else 
            p_src_data_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln303_reg_544, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln303_1_reg_553, ap_block_pp0_stage0_11001, ap_block_pp1_stage0_11001, ap_CS_fsm_state13, grp_process_row_fu_326_p_src_data_V_V_read)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln303_reg_544 = ap_const_lv1_0)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln303_1_reg_553 = ap_const_lv1_0)))) then 
            p_src_data_V_V_read <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            p_src_data_V_V_read <= grp_process_row_fu_326_p_src_data_V_V_read;
        else 
            p_src_data_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_510_p2 <= std_logic_vector(unsigned(r3_0_reg_314) + unsigned(ap_const_lv16_1));
    shl_ln_fu_396_p3 <= (trunc_ln_fu_386_p4 & ap_const_lv1_0);
    trunc_ln_fu_386_p4 <= add_ln113_fu_380_p2(16 downto 1);
    zext_ln113_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_src_cols_read),17));
    zext_ln301_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_396_p3),32));
    zext_ln306_1_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_1_reg_198),64));
    zext_ln306_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_0_reg_186),64));
    zext_ln317_1_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c2_0_1_reg_221),64));
    zext_ln317_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c2_0_0_reg_210),64));
    zext_ln325_1_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r3_0_reg_314),17));
    zext_ln325_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_src_rows_read),17));
end behav;
