// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        aecin_4202_dout,
        aecin_4202_empty_n,
        aecin_4202_read,
        p_dst_4201_din,
        p_dst_4201_full_n,
        p_dst_4201_write,
        gamma_lut_address0,
        gamma_lut_ce0,
        gamma_lut_q0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_read;
input  [11:0] p_read1;
input  [47:0] aecin_4202_dout;
input   aecin_4202_empty_n;
output   aecin_4202_read;
output  [47:0] p_dst_4201_din;
input   p_dst_4201_full_n;
output   p_dst_4201_write;
output  [9:0] gamma_lut_address0;
output   gamma_lut_ce0;
input  [7:0] gamma_lut_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg aecin_4202_read;
reg p_dst_4201_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg   [10:0] width_cast_reg_173;
reg   [7:0] lut_0_0_address0;
reg    lut_0_0_ce0;
reg    lut_0_0_we0;
wire   [7:0] lut_0_0_q0;
reg   [7:0] lut_0_1_address0;
reg    lut_0_1_ce0;
reg    lut_0_1_we0;
wire   [7:0] lut_0_1_q0;
reg   [7:0] lut_1_0_address0;
reg    lut_1_0_ce0;
reg    lut_1_0_we0;
wire   [7:0] lut_1_0_q0;
reg   [7:0] lut_1_1_address0;
reg    lut_1_1_ce0;
reg    lut_1_1_we0;
wire   [7:0] lut_1_1_q0;
reg   [7:0] lut_2_0_address0;
reg    lut_2_0_ce0;
reg    lut_2_0_we0;
wire   [7:0] lut_2_0_q0;
reg   [7:0] lut_2_1_address0;
reg    lut_2_1_ce0;
reg    lut_2_1_we0;
wire   [7:0] lut_2_1_q0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_done;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_idle;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_ready;
wire   [9:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_d0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_d0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_d0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_d0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_d0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_ce0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_we0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_d0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_done;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_idle;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_ready;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_aecin_4202_read;
wire   [47:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_din;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_write;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_ce0;
wire   [7:0] grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_address0;
wire    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_ce0;
reg    grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg;
reg    ap_block_state1_ignore_call13;
reg    grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln53_fu_151_p2;
wire    ap_CS_fsm_state4;
reg   [11:0] i_V_2_fu_54;
wire   [11:0] i_V_3_fu_145_p2;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg = 1'b0;
#0 grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg = 1'b0;
end

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_0_0_address0),
    .ce0(lut_0_0_ce0),
    .we0(lut_0_0_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_d0),
    .q0(lut_0_0_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_0_1_address0),
    .ce0(lut_0_1_ce0),
    .we0(lut_0_1_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_d0),
    .q0(lut_0_1_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_1_0_address0),
    .ce0(lut_1_0_ce0),
    .we0(lut_1_0_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_d0),
    .q0(lut_1_0_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_1_1_address0),
    .ce0(lut_1_1_ce0),
    .we0(lut_1_1_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_d0),
    .q0(lut_1_1_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_2_0_address0),
    .ce0(lut_2_0_ce0),
    .we0(lut_2_0_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_d0),
    .q0(lut_2_0_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s_lut_0_0 #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
lut_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_2_1_address0),
    .ce0(lut_2_1_ce0),
    .we0(lut_2_1_we0),
    .d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_d0),
    .q0(lut_2_1_q0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2 grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start),
    .ap_done(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_done),
    .ap_idle(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_idle),
    .ap_ready(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_ready),
    .gamma_lut_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_address0),
    .gamma_lut_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_ce0),
    .gamma_lut_q0(gamma_lut_q0),
    .lut_2_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_address0),
    .lut_2_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_ce0),
    .lut_2_0_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_we0),
    .lut_2_0_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_d0),
    .lut_2_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_address0),
    .lut_2_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_ce0),
    .lut_2_1_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_we0),
    .lut_2_1_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_d0),
    .lut_1_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_address0),
    .lut_1_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_ce0),
    .lut_1_0_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_we0),
    .lut_1_0_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_d0),
    .lut_1_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_address0),
    .lut_1_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_ce0),
    .lut_1_1_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_we0),
    .lut_1_1_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_d0),
    .lut_0_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_address0),
    .lut_0_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_ce0),
    .lut_0_0_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_we0),
    .lut_0_0_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_d0),
    .lut_0_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_address0),
    .lut_0_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_ce0),
    .lut_0_1_we0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_we0),
    .lut_0_1_d0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_d0)
);

ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start),
    .ap_done(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_done),
    .ap_idle(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_idle),
    .ap_ready(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_ready),
    .aecin_4202_dout(aecin_4202_dout),
    .aecin_4202_empty_n(aecin_4202_empty_n),
    .aecin_4202_read(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_aecin_4202_read),
    .p_dst_4201_din(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_din),
    .p_dst_4201_full_n(p_dst_4201_full_n),
    .p_dst_4201_write(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_write),
    .width_cast(width_cast_reg_173),
    .lut_0_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_address0),
    .lut_0_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_ce0),
    .lut_0_0_q0(lut_0_0_q0),
    .lut_1_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_address0),
    .lut_1_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_ce0),
    .lut_1_0_q0(lut_1_0_q0),
    .lut_2_0_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_address0),
    .lut_2_0_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_ce0),
    .lut_2_0_q0(lut_2_0_q0),
    .lut_0_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_address0),
    .lut_0_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_ce0),
    .lut_0_1_q0(lut_0_1_q0),
    .lut_1_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_address0),
    .lut_1_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_ce0),
    .lut_1_1_q0(lut_1_1_q0),
    .lut_2_1_address0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_address0),
    .lut_2_1_ce0(grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_ce0),
    .lut_2_1_q0(lut_2_1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_ready == 1'b1)) begin
            grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd0))) begin
            grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_ready == 1'b1)) begin
            grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_V_2_fu_54 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd0))) begin
        i_V_2_fu_54 <= i_V_3_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        width_cast_reg_173 <= {{p_read1[11:1]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        aecin_4202_read = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_aecin_4202_read;
    end else begin
        aecin_4202_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_address0;
    end else begin
        lut_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_ce0;
    end else begin
        lut_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_0_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_0_we0;
    end else begin
        lut_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_address0;
    end else begin
        lut_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_ce0;
    end else begin
        lut_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_1_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_0_1_we0;
    end else begin
        lut_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_address0;
    end else begin
        lut_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_ce0;
    end else begin
        lut_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_0_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_0_we0;
    end else begin
        lut_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_address0;
    end else begin
        lut_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_ce0;
    end else begin
        lut_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_1_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_1_1_we0;
    end else begin
        lut_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_0_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_address0;
    end else begin
        lut_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_0_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_ce0;
    end else begin
        lut_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_0_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_0_we0;
    end else begin
        lut_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_1_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_address0;
    end else begin
        lut_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_lut_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_1_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_ce0;
    end else begin
        lut_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_1_we0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_lut_2_1_we0;
    end else begin
        lut_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_dst_4201_write = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_write;
    end else begin
        p_dst_4201_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln53_fu_151_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign gamma_lut_address0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_address0;

assign gamma_lut_ce0 = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_gamma_lut_ce0;

assign grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start = grp_gammacorrection_9_9_2160_3840_2_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_94_ap_start_reg;

assign grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_ap_start_reg;

assign i_V_3_fu_145_p2 = (i_V_2_fu_54 + 12'd1);

assign icmp_ln53_fu_151_p2 = ((i_V_2_fu_54 == p_read) ? 1'b1 : 1'b0);

assign p_dst_4201_din = grp_gammacorrection_9_9_2160_3840_2_Pipeline_colLoop_fu_112_p_dst_4201_din;

endmodule //ISPPipeline_accel_gammacorrection_9_9_2160_3840_2_s
