// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.2
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module process_image (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1,
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1,
        p_src_rows_read,
        p_src_cols_read,
        p_src_data_V_V_dout,
        p_src_data_V_V_empty_n,
        p_src_data_V_V_read,
        p_dst_data_V_V_din,
        p_dst_data_V_V_full_n,
        p_dst_data_V_V_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_pp0_stage0 = 11'd2;
parameter    ap_ST_fsm_state4 = 11'd4;
parameter    ap_ST_fsm_pp1_stage0 = 11'd8;
parameter    ap_ST_fsm_state7 = 11'd16;
parameter    ap_ST_fsm_state8 = 11'd32;
parameter    ap_ST_fsm_state9 = 11'd64;
parameter    ap_ST_fsm_state10 = 11'd128;
parameter    ap_ST_fsm_state11 = 11'd256;
parameter    ap_ST_fsm_state12 = 11'd512;
parameter    ap_ST_fsm_state13 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0;
input  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1;
output  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0;
input  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1;
output  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0;
input  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1;
output  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0;
input  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1;
output  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0;
input  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0;
output  [9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1;
output   GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1;
output  [19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1;
input  [15:0] p_src_rows_read;
input  [15:0] p_src_cols_read;
input  [19:0] p_src_data_V_V_dout;
input   p_src_data_V_V_empty_n;
output   p_src_data_V_V_read;
output  [19:0] p_dst_data_V_V_din;
input   p_dst_data_V_V_full_n;
output   p_dst_data_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0;
reg[9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1;
reg[19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0;
reg[9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1;
reg[19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0;
reg[9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1;
reg[19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0;
reg[9:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1;
reg GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1;
reg[19:0] GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1;
reg p_src_data_V_V_read;
reg p_dst_data_V_V_write;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln303_reg_544;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln303_1_reg_553;
reg   [15:0] c_0_0_reg_186;
reg   [15:0] c_0_1_reg_198;
wire   [15:0] trunc_ln_fu_386_p4;
reg   [15:0] trunc_ln_reg_530;
wire   [31:0] zext_ln301_fu_404_p1;
reg   [31:0] zext_ln301_reg_539;
wire   [0:0] icmp_ln303_fu_408_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln303_fu_413_p2;
reg   [15:0] add_ln303_reg_548;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln303_1_fu_424_p2;
wire    ap_block_state5_pp1_stage0_iter0;
reg    ap_block_state6_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [15:0] add_ln303_1_fu_429_p2;
reg   [15:0] add_ln303_1_reg_557;
reg    ap_enable_reg_pp1_iter0;
wire   [15:0] add_ln314_fu_445_p2;
wire    ap_CS_fsm_state8;
wire   [15:0] add_ln314_1_fu_461_p2;
wire    ap_CS_fsm_state10;
wire   [16:0] add_ln325_fu_475_p2;
reg   [16:0] add_ln325_reg_578;
wire    ap_CS_fsm_state11;
reg   [7:0] GenericBPC_row_idx_v_5_reg_586;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln325_fu_485_p2;
reg   [7:0] GenericBPC_row_idx_v_6_reg_591;
reg   [7:0] GenericBPC_row_idx_v_7_reg_596;
reg   [7:0] GenericBPC_row_idx_v_8_reg_601;
reg   [7:0] GenericBPC_row_idx_v_9_reg_606;
wire   [15:0] r_fu_510_p2;
reg   [15:0] r_reg_611;
wire    ap_CS_fsm_state13;
wire    grp_process_row_fu_326_ap_ready;
wire    grp_process_row_fu_326_ap_done;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_CS_fsm_state4;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state5;
wire    grp_process_row_fu_326_ap_start;
wire    grp_process_row_fu_326_ap_idle;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1;
wire   [19:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1;
wire   [19:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1;
wire   [19:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1;
wire   [19:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0;
wire   [9:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1;
wire    grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1;
wire   [19:0] grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1;
wire    grp_process_row_fu_326_p_src_data_V_V_read;
wire   [19:0] grp_process_row_fu_326_p_dst_data_V_V_din;
wire    grp_process_row_fu_326_p_dst_data_V_V_write;
wire   [31:0] grp_process_row_fu_326_ap_return_0;
wire   [31:0] grp_process_row_fu_326_ap_return_1;
wire    call_ret5_update_row_idx_fu_362_ap_ready;
wire   [7:0] call_ret5_update_row_idx_fu_362_ap_return_0;
wire   [7:0] call_ret5_update_row_idx_fu_362_ap_return_1;
wire   [7:0] call_ret5_update_row_idx_fu_362_ap_return_2;
wire   [7:0] call_ret5_update_row_idx_fu_362_ap_return_3;
wire   [7:0] call_ret5_update_row_idx_fu_362_ap_return_4;
reg   [15:0] ap_phi_mux_c_0_0_phi_fu_190_p4;
reg   [15:0] ap_phi_mux_c_0_1_phi_fu_202_p4;
reg   [15:0] c2_0_0_reg_210;
wire   [0:0] icmp_ln314_fu_440_p2;
wire    ap_CS_fsm_state7;
reg   [15:0] c2_0_1_reg_221;
wire   [0:0] icmp_ln314_1_fu_456_p2;
wire    ap_CS_fsm_state9;
reg   [7:0] GenericBPC_row_idx_v_reg_232;
reg   [7:0] GenericBPC_row_idx_v_1_reg_244;
reg   [7:0] GenericBPC_row_idx_v_2_reg_256;
reg   [7:0] GenericBPC_row_idx_v_3_reg_268;
reg   [7:0] GenericBPC_row_idx_v_4_reg_280;
reg   [31:0] GenericBPC_rd_ptr_reg_292;
reg   [31:0] GenericBPC_wr_ptr_0_reg_302;
reg   [15:0] r3_0_reg_314;
reg    grp_process_row_fu_326_ap_start_reg;
wire   [63:0] zext_ln306_fu_419_p1;
wire   [63:0] zext_ln306_1_fu_435_p1;
wire   [63:0] zext_ln317_fu_451_p1;
wire   [63:0] zext_ln317_1_fu_467_p1;
wire   [16:0] zext_ln113_fu_376_p1;
wire   [16:0] add_ln113_fu_380_p2;
wire   [16:0] shl_ln_fu_396_p3;
wire   [16:0] zext_ln325_fu_472_p1;
wire   [16:0] zext_ln325_1_fu_481_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 grp_process_row_fu_326_ap_start_reg = 1'b0;
end

process_row grp_process_row_fu_326(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_row_fu_326_ap_start),
    .ap_done(grp_process_row_fu_326_ap_done),
    .ap_idle(grp_process_row_fu_326_ap_idle),
    .ap_ready(grp_process_row_fu_326_ap_ready),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read(GenericBPC_row_idx_v_reg_232),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read(GenericBPC_row_idx_v_1_reg_244),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read(GenericBPC_row_idx_v_2_reg_256),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read(GenericBPC_row_idx_v_3_reg_268),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read(GenericBPC_row_idx_v_4_reg_280),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0(GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_q0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0(GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_q0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0(GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_q0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0(GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_q0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0(GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_q0),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1(grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_num_clks_per_row_read(trunc_ln_reg_530),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_rd_ptr_read(GenericBPC_rd_ptr_reg_292),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_wr_ptr_read(GenericBPC_wr_ptr_0_reg_302),
    .r(r3_0_reg_314),
    .p_src_rows_read(p_src_rows_read),
    .p_src_data_V_V_dout(p_src_data_V_V_dout),
    .p_src_data_V_V_empty_n(p_src_data_V_V_empty_n),
    .p_src_data_V_V_read(grp_process_row_fu_326_p_src_data_V_V_read),
    .p_dst_data_V_V_din(grp_process_row_fu_326_p_dst_data_V_V_din),
    .p_dst_data_V_V_full_n(p_dst_data_V_V_full_n),
    .p_dst_data_V_V_write(grp_process_row_fu_326_p_dst_data_V_V_write),
    .ap_return_0(grp_process_row_fu_326_ap_return_0),
    .ap_return_1(grp_process_row_fu_326_ap_return_1)
);

update_row_idx call_ret5_update_row_idx_fu_362(
    .ap_ready(call_ret5_update_row_idx_fu_362_ap_ready),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_0_read(GenericBPC_row_idx_v_reg_232),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_1_read(GenericBPC_row_idx_v_1_reg_244),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_2_read(GenericBPC_row_idx_v_2_reg_256),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_3_read(GenericBPC_row_idx_v_3_reg_268),
    .GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_row_idx_val_4_read(GenericBPC_row_idx_v_4_reg_280),
    .ap_return_0(call_ret5_update_row_idx_fu_362_ap_return_0),
    .ap_return_1(call_ret5_update_row_idx_fu_362_ap_return_1),
    .ap_return_2(call_ret5_update_row_idx_fu_362_ap_return_2),
    .ap_return_3(call_ret5_update_row_idx_fu_362_ap_return_3),
    .ap_return_4(call_ret5_update_row_idx_fu_362_ap_return_4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state5))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_row_fu_326_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln325_fu_485_p2 == 1'd1))) begin
            grp_process_row_fu_326_ap_start_reg <= 1'b1;
        end else if ((grp_process_row_fu_326_ap_ready == 1'b1)) begin
            grp_process_row_fu_326_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_rd_ptr_reg_292 <= zext_ln301_reg_539;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_rd_ptr_reg_292 <= grp_process_row_fu_326_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_row_idx_v_1_reg_244 <= 8'd1;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_row_idx_v_1_reg_244 <= GenericBPC_row_idx_v_6_reg_591;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_row_idx_v_2_reg_256 <= 8'd2;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_row_idx_v_2_reg_256 <= GenericBPC_row_idx_v_7_reg_596;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_row_idx_v_3_reg_268 <= 8'd3;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_row_idx_v_3_reg_268 <= GenericBPC_row_idx_v_8_reg_601;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_row_idx_v_4_reg_280 <= 8'd4;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_row_idx_v_4_reg_280 <= GenericBPC_row_idx_v_9_reg_606;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_row_idx_v_reg_232 <= 8'd0;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_row_idx_v_reg_232 <= GenericBPC_row_idx_v_5_reg_586;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        GenericBPC_wr_ptr_0_reg_302 <= 32'd0;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        GenericBPC_wr_ptr_0_reg_302 <= grp_process_row_fu_326_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        c2_0_0_reg_210 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln314_fu_440_p2 == 1'd0))) begin
        c2_0_0_reg_210 <= add_ln314_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        c2_0_1_reg_221 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln314_1_fu_456_p2 == 1'd0))) begin
        c2_0_1_reg_221 <= add_ln314_1_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln303_reg_544 == 1'd0))) begin
        c_0_0_reg_186 <= add_ln303_reg_548;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_0_0_reg_186 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_0_1_reg_198 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln303_1_reg_553 == 1'd0))) begin
        c_0_1_reg_198 <= add_ln303_1_reg_557;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        r3_0_reg_314 <= 16'd2;
    end else if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        r3_0_reg_314 <= r_reg_611;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln325_fu_485_p2 == 1'd1))) begin
        GenericBPC_row_idx_v_5_reg_586 <= call_ret5_update_row_idx_fu_362_ap_return_0;
        GenericBPC_row_idx_v_6_reg_591 <= call_ret5_update_row_idx_fu_362_ap_return_1;
        GenericBPC_row_idx_v_7_reg_596 <= call_ret5_update_row_idx_fu_362_ap_return_2;
        GenericBPC_row_idx_v_8_reg_601 <= call_ret5_update_row_idx_fu_362_ap_return_3;
        GenericBPC_row_idx_v_9_reg_606 <= call_ret5_update_row_idx_fu_362_ap_return_4;
        r_reg_611 <= r_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        add_ln303_1_reg_557 <= add_ln303_1_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln303_reg_548 <= add_ln303_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln325_reg_578 <= add_ln325_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln303_1_reg_553 <= icmp_ln303_1_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln303_reg_544 <= icmp_ln303_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        trunc_ln_reg_530 <= {{add_ln113_fu_380_p2[16:1]}};
        zext_ln301_reg_539[16 : 1] <= zext_ln301_fu_404_p1[16 : 1];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 = zext_ln317_fu_451_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 = 20'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln314_fu_440_p2 == 1'd0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 = zext_ln317_1_fu_467_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 = 20'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln314_1_fu_456_p2 == 1'd0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 = zext_ln306_fu_419_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 = p_src_data_V_V_dout;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln303_reg_544 == 1'd0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 = zext_ln306_1_fu_435_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 = p_src_data_V_V_dout;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln303_1_reg_553 == 1'd0))) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1;
    end else begin
        GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln303_fu_408_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln303_1_fu_424_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (icmp_ln325_fu_485_p2 == 1'd0)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln303_reg_544 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_c_0_0_phi_fu_190_p4 = add_ln303_reg_548;
    end else begin
        ap_phi_mux_c_0_0_phi_fu_190_p4 = c_0_0_reg_186;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0) & (icmp_ln303_1_reg_553 == 1'd0))) begin
        ap_phi_mux_c_0_1_phi_fu_202_p4 = add_ln303_1_reg_557;
    end else begin
        ap_phi_mux_c_0_1_phi_fu_202_p4 = c_0_1_reg_198;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln325_fu_485_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_dst_data_V_V_write = grp_process_row_fu_326_p_dst_data_V_V_write;
    end else begin
        p_dst_data_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln303_reg_544 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0) & (icmp_ln303_1_reg_553 == 1'd0)))) begin
        p_src_data_V_V_blk_n = p_src_data_V_V_empty_n;
    end else begin
        p_src_data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln303_reg_544 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln303_1_reg_553 == 1'd0)))) begin
        p_src_data_V_V_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        p_src_data_V_V_read = grp_process_row_fu_326_p_src_data_V_V_read;
    end else begin
        p_src_data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln303_fu_408_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln303_fu_408_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln303_1_fu_424_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln303_1_fu_424_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln314_fu_440_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln314_1_fu_456_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln325_fu_485_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((grp_process_row_fu_326_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_0_V_address0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_1_V_address0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_2_V_address0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_3_V_address0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_address1;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce0;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_ce1;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_d1;

assign GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1 = grp_process_row_fu_326_GenericBPC_xf_cv_BPC_13_2_13_1080_1920_5_5_2_0_0_buff_val_4_V_we1;

assign add_ln113_fu_380_p2 = (zext_ln113_fu_376_p1 + 17'd1);

assign add_ln303_1_fu_429_p2 = (ap_phi_mux_c_0_1_phi_fu_202_p4 + 16'd1);

assign add_ln303_fu_413_p2 = (ap_phi_mux_c_0_0_phi_fu_190_p4 + 16'd1);

assign add_ln314_1_fu_461_p2 = (c2_0_1_reg_221 + 16'd1);

assign add_ln314_fu_445_p2 = (c2_0_0_reg_210 + 16'd1);

assign add_ln325_fu_475_p2 = (zext_ln325_fu_472_p1 + 17'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((p_src_data_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln303_reg_544 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((p_src_data_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln303_reg_544 == 1'd0));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((p_src_data_V_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln303_1_reg_553 == 1'd0));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((p_src_data_V_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln303_1_reg_553 == 1'd0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((p_src_data_V_V_empty_n == 1'b0) & (icmp_ln303_reg_544 == 1'd0));
end

assign ap_block_state5_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp1_stage0_iter1 = ((p_src_data_V_V_empty_n == 1'b0) & (icmp_ln303_1_reg_553 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign grp_process_row_fu_326_ap_start = grp_process_row_fu_326_ap_start_reg;

assign icmp_ln303_1_fu_424_p2 = ((ap_phi_mux_c_0_1_phi_fu_202_p4 == trunc_ln_reg_530) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_408_p2 = ((ap_phi_mux_c_0_0_phi_fu_190_p4 == trunc_ln_reg_530) ? 1'b1 : 1'b0);

assign icmp_ln314_1_fu_456_p2 = ((c2_0_1_reg_221 == trunc_ln_reg_530) ? 1'b1 : 1'b0);

assign icmp_ln314_fu_440_p2 = ((c2_0_0_reg_210 == trunc_ln_reg_530) ? 1'b1 : 1'b0);

assign icmp_ln325_fu_485_p2 = ((zext_ln325_1_fu_481_p1 < add_ln325_reg_578) ? 1'b1 : 1'b0);

assign p_dst_data_V_V_din = grp_process_row_fu_326_p_dst_data_V_V_din;

assign r_fu_510_p2 = (r3_0_reg_314 + 16'd1);

assign shl_ln_fu_396_p3 = {{trunc_ln_fu_386_p4}, {1'd0}};

assign trunc_ln_fu_386_p4 = {{add_ln113_fu_380_p2[16:1]}};

assign zext_ln113_fu_376_p1 = p_src_cols_read;

assign zext_ln301_fu_404_p1 = shl_ln_fu_396_p3;

assign zext_ln306_1_fu_435_p1 = c_0_1_reg_198;

assign zext_ln306_fu_419_p1 = c_0_0_reg_186;

assign zext_ln317_1_fu_467_p1 = c2_0_1_reg_221;

assign zext_ln317_fu_451_p1 = c2_0_0_reg_210;

assign zext_ln325_1_fu_481_p1 = r3_0_reg_314;

assign zext_ln325_fu_472_p1 = p_src_rows_read;

always @ (posedge ap_clk) begin
    zext_ln301_reg_539[0] <= 1'b0;
    zext_ln301_reg_539[31:17] <= 15'b000000000000000;
end

endmodule //process_image
